export const BANK_CARD = 'BANK_CARD';


export const BANK_SUPPORT_LIST = 'BANK_SUPPORT_LIST';

export const PAY_TYPE = 'PAY_TYPE';

export const BANK_SUPPORT_CHANNEL = 'BANK_SUPPORT_CHANNEL';

export const BIND_CARD_CALLBACK_URL = 'BIND_CARD_CALLBACK_URL';

export const IS_THIRD_BIND = 'IS_THIRD_BIND';

export const SMS_CODE_SUCCESS = 'SMS_CODE_SUCCESS';

export const CARD_AGREEMENT = 'CARD_AGREEMENT';
