export const GET_ORDER_STATUS = "GET_ORDER_STATUS";
export const PLACE_ORDER = "PLACE_ORDER";
export const GET_ORDER_CALCULATE = "GET_ORDER_CALCULATE";
export const GET_ORDER_PLAN = "GET_ORDER_PLAN";
export const GET_WITHDRAW_RULES = "GET_WITHDRAW_RULES";
export const GET_INFORMATION = "GET_INFORMATION";
export const COMMIT_INFORMATION = "COMMIT_INFORMATION";
export const GET_COMPANY_INFO = "GET_COMPANY_INFO";
export const GET_PROVINCES = "GET_PROVINCES";
export const GET_CITYS = "GET_CITYS";
export const GET_DISTRICTS = "GET_DISTRICTS";
export const GET_LEGAODICT = "GET_LEGAODICT";
export const GET_FACE_URL = "GET_FACE_URL";
export const GET_CONTRACT_URL = "GET_CONTRACT_URL";

