export const ORDER_STATUS = "ORDER_STATUS";
export const LOAN_INFO = "LOAN_INFO";
export const ORDER_CALCULATE = "ORDER_CALCULATE";
export const ORDER_PLAN = "ORDER_PLAN";
export const WITHDRAW_RULES = "WITHDRAW_RULES";
export const INFORMATION = "INFORMATION";
export const COMPANY_INFO = "COMPANY_INFO";
export const PROVINCES = "PROVINCES";
export const CITYS = "CITYS";
export const DISTRICTS = "DISTRICTS";
export const LEGAODICT = "LEGAODICT";
export const GET_FACE_INFO = "FACE_INFO"
export const CONTRACTURL = "CONTRACTURL"
export const CUSTRELATIONDIST = "CUSTRELATIONDIST"
export const INDUSTRYCATEGORYLIST = "INDUSTRYCATEGORYLIST"
export const SOURCEOFINCOMEDIST = "SOURCEOFINCOMEDIST"


