export const QUERY_LOAN_INFO_SUCCESS = "QUERY_LOAN_INFO_SUCCESS"
export const QUERY_LOAN_INFO_FAILD = "QUERY_LOAN_INFO_FAILD"
export const GET_WITHDRAW_RULES_SUCCESS = "GET_WITHDRAW_RULES_SUCCESS"
export const QUERY_ORDER_CALCULATE_SUCCESS = "QUERY_ORDER_CALCULATE_SUCCESS"
export const QUERY_ORDER_PLAN_SUCCESS = "QUERY_ORDER_PLAN_SUCCESS"
export const SAVE_USER_BASE_INFO = "SAVE_USER_BASE_INFO"
export const QUERY_INFORMATION_SUCCESS = "QUERY_INFORMATION_SUCCESS"
export const QUERY_COMPANY_INFO_SUCCESS = "QUERY_COMPANY_INFO_SUCCESS"
export const QUERY_PROVINCES_SUCCESS = "QUERY_PROVINCES_SUCCESS"
export const QUERY_CITYS_SUCCESS = "QUERY_CITYS_SUCCESS"
export const QUERY_LEGAODICT_SUCCESS = "QUERY_LEGAODICT_SUCCESS"
export const QUERY_DISTRICTS_SUCCESS = "QUERY_DISTRICTS_SUCCESS"
export const QUERY_FACE_SUCCESS = "QUERY_FACE_SUCCESS"
export const CLEAR_ORDER_INFO = "CLEAR_ORDER_INFO"
export const QUERY_CONTRACT_URL_SUCCESS = "QUERY_CONTRACT_URL_SUCCESS"



