export const SMS_CODE_STATUS = 'SMS_CODE_STATUS';
export const CAPTCHA_JS_URL = 'CAPTCHA_JS_URL';
export const CAPTCHA_TICKET = 'CAPTCHA_TICKET';
export const CAPTCHA_SHOW = 'CAPTCHA_SHOW';
export const CHECK_SMS_CODE_TOKEN = 'CHECK_SMS_CODE_TOKEN';
