export const SET_SMS_CODE_STATUS = 'SET_SMS_CODE_STATUS';
export const SET_CAPTCHA_JS_URL = 'SET_CAPTCHA_JS_URL';
export const SET_CAPTCHA_TICKET = 'SET_CAPTCHA_TICKET';
export const SET_CAPTCHA_SHOW = 'SET_CAPTCHA_SHOW';
export const SET_CHECK_SMS_CODE_TOKEN = 'SET_CHECK_SMS_CODE_TOKEN';




