export const GET_WITHDRAW_DEPOSITINFO = "GET_WITHDRAW_DEPOSITINFO";
export const SUBMIT_WITHDRAW_DEPOSITINFO = "WITHDRAW_DEPOSITINFO";
export const MODIFY_PASSWORD = "MODIFY_PASSWORD";
export const UN_LOCKING = "UN_LOCKING";